### ISSUE TITLE
Violates LGPL

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [SynnKFPS/sodium-plus#1]
After checking the difference between this project and CaffeineMC/sodium-fabric I have not found any differences in the code, although after de-compiling the binaries in the releases section of this github repository, it seems that the binaries definitely contain other code, which is also obvious simply through the extra options in the video settings menu. The LGPL-3.0 license requires you to provide the code for any binaries that you provide, which you haven't done. The GNU Lesser General Public License (3.0) also requires you to state the original source, yet you have overwritten the git version control system to keep all of the code under one initial commit in your name, and have stripped all links to the original sodium from the README.

**Comment by spencer1911** [comment]
I added a extra tab.

Em Dom, 29 de ago de 2021 09:28, DragonEggBedrockBreaking <
***@***.***> escreveu:

**Comment by DragonEggBedrockBreaking** [comment]
Oh wait, never mind, I looked through the code again and it seems my diff tool was a bit faulty…
